source 'https://rubygems.org'

gem 'awesome_print'
gem 'puma'
gem 'rails', '~> 4.0'
gem 'rails_semantic_logger', '>= 4.0.0'

gem 'rocketjob_mission_control', path: '../'

# For local testing
#gem 'rocketjob', path: '../../rocketjob'
#gem 'rocketjob_pro', path: '../../rocketjob_pro'
