source 'https://rubygems.org'

gem 'rails', '~> 4.2.0'
gem 'rails_semantic_logger', '~> 4.0'
gem 'mongo_ha', '~> 2.6'
gem 'puma'
gem 'awesome_print'

gem 'rocketjob_mission_control', path: '../'

# For testing with local copies of the gems:
#gem 'rocketjob', path: '../../rocketjob'
#gem 'rocketjob_pro', path: '../../rocketjob_pro'
